---
title: "Repeat victimization by website defacement: An empirical test of premises from an environmental criminology perspective"
description: Journal article
base_url: https://amoneva.github.io/
author:
  - name: Asier Moneva
    affiliation: Netherlands Institute for the Study of Crime and Law Enforcement (NSCR) & Centre of Expertise Cyber Security at The Hague University of Applied Sciences
    orcid_id: https://orcid.org/0000-0002-2156-0213
  - name: E. Rutger Leukfeldt
    affiliation: Netherlands Institute for the Study of Crime and Law Enforcement (NSCR) & Centre of Expertise Cyber Security at The Hague University of Applied Sciences
    orcid_id: https://orcid.org/0000-0002-3051-0859
  - name: Steve G.A. van de Weijer
    affiliation: Netherlands Institute for the Study of Crime and Law Enforcement (NSCR)
    orcid_id: https://orcid.org/0000-0001-5914-5966
  - name: Fernando Miró-Llinares
    affiliation: Crimina Center for the Study and Prevention of Crime at Miguel Hernandez University
date: 2021-08-18
categories:
  - cybercrime
  - environmental criminology
  - hacking
  - repeat victimization
  - website defacement
  - zone-h
doi: https://doi.org/10.1016/j.chb.2021.106984
citation: false
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Abstract

Repeat victimization has been widely studied from the perspective of environmental criminology for several decades. During this period, criminologists have identified a set of repeat victimization premises that are observed for many crimes; however, it is unknown whether these premises are also valid for cybercrime. In this study we rely on more than 9 million Zone-H data records from 2010 to 2017 to test whether these premises apply for the cybercrime of website defacement. We show that the phenomenon of repeat victimization is also observed in defaced cyber places (i.e. websites). In particular, we found that repeats contributed little to crime rates, that repeats occurred even several years after the original incident, that they were committed disproportionately by prolific offenders, and that few offenders returned to victimize previous targets. The results suggest that some traditional premises of repeat victimization may also be valid for understanding cybercrime events such as website defacement, implying that environmental criminology theories also constitute a useful framework for cybercrime analysis. The implications of these results in terms of criminological theory, cybercrime prevention, and the limitations derived from the use of Zone-H data are discussed.

# Links

-   [Access the R code](https://github.com/amoneva/code_papers)
-   [Read the paper online](https://www.sciencedirect.com/science/article/pii/S0747563221003071)
-   [Download the PDF](moneva_2021_repeat_victimization_by_website_defacement.pdf)
