---
title: "Pathways into, desistance from, and risk factors related to cyber-dependent crime: a systematic narrative review"
description: Journal article
base_url: https://amoneva.github.io/
preview: preview.png
author:
  - name: Joeri Loggen
    affiliation: Centre of Expertise Cyber Security at The Hague University of Applied Sciences
    orcid_id: https://orcid.org/0000-0001-9038-8931
  - name: Asier Moneva
    affiliation: Netherlands Institute for the Study of Crime and Law Enforcement (NSCR) & Centre of Expertise Cyber Security at The Hague University of Applied Sciences
    orcid_id: https://orcid.org/0000-0002-2156-0213
  - name: E. Rutger Leukfeldt
    affiliation: Netherlands Institute for the Study of Crime and Law Enforcement (NSCR) & Centre of Expertise Cyber Security at The Hague University of Applied Sciences & Institute of Security and Global Affairs and Institute of Criminal Law and Criminology at Leiden University
    orcid_id: https://orcid.org/0000-0002-3051-0859
# Publication date (online first)
date: 2024-06-28
categories:
  - developmental criminology
  - individual offenders
  - cyber-dependent crime
  - hacking
  - qualitative methods
doi: https://doi.org/10.1080/15564886.2024.2370295
citation: false
output:
  distill::distill_article:
    toc: true
    self_contained: false
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Abstract

Cyber-dependent crime is a growing global threat. However, research on cybercrime offending throughout the life course, especially on the factors leading to initiation and desistance of cyber-dependent crime remains underdeveloped. This paper synthesizes the literature on pathways into, desistance from, and risk factors related to cyber-dependent crime (hacking, malware, and DDoS attacks), and identifies research gaps. Following PRISMA-ScR guidelines, we conducted a systematic search and identified 86 eligible documents published as of February 2022. Results reveal a pathway into hacking through interest in technology and online videogames, which continues with social learning from peers involved in hacking activities, and thus leads to the world of cybercrime. Desistance from this pathway is influenced by a cost-benefit analysis and maturing. We also identified 27 risk factors for the initiation process in cyber-offending that are consistent in the literature. The most significant ones were being young, male, having low self-control, deviant peers, and frequently using the Internet.

# Links

-   [Read the paper online](https://www.tandfonline.com/doi/abs/10.1080/15564886.2024.2370295)
-   [Download the PDF (pre-print)](https://doi.org/10.31219/osf.io/kpfrb)
-   [Read the protocol online](https://doi.org/10.17605/OSF.IO/MJZEA)
