---
title: "Alerting consciences to reduce cybercrime: A quasi-experimental design using warning banners"
description: Journal article
base_url: https://amoneva.github.io/
preview: preview.png
author:
  - name: Asier Moneva
    affiliation: Netherlands Institute for the Study of Crime and Law Enforcement (NSCR) & Centre of Expertise Cyber Security at The Hague University of Applied Sciences
    orcid_id: https://orcid.org/0000-0002-2156-0213
  - name: E. Rutger Leukfeldt
    affiliation: Netherlands Institute for the Study of Crime and Law Enforcement (NSCR) & Centre of Expertise Cyber Security at The Hague University of Applied Sciences
    orcid_id: https://orcid.org/0000-0002-3051-0859
  - name: Wouter Klijnsoon
    affiliation: Team High Tech Crime (THTC) at Dutch National Police
    orcid_id: https://orcid.org/0000-0001-5263-4492
# Publication date (online first)
date: 2022-03-24
categories:
  - environmental criminology
  - individual offenders
  - cyber-dependent crime
  - DDoS-attacks
  - quantitative methods
doi: https://doi.org/10.1007/s11292-022-09504-2
citation: false
output:
  distill::distill_article:
    toc: true
    self_contained: false
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Abstract

Objective: Aiming to reduce distributed denial-of-service (DDoS) attacks by alerting the consciences of Internet users, this paper evaluates the effectiveness of four warning banners displayed as online ads (deterrent—control, social, informative, and reorienting) and the contents of their two linked landing pages.

Methods: We implement a 4 × 2 quasi-experimental design on a self-selected sample of Internet users to measure the engagement generated by the ads and the pages. Engagement is measured on the ads as the ratio of clicks to impressions and on the pages as percentage of page scrolled, average session duration, video interaction rate, and URLs click rate.

Results: Social ads generate significantly more engagement than the rest with low to medium effect sizes. Data reveal no differences in engagement between both landing page designs.

Conclusions: Social messages may be a better alternative for engaging with potential cyber offenders than the traditional deterrent messages.

# Links

-   [Read the paper online](https://link.springer.com/article/10.1007/s11292-022-09504-2)
-   [Download the PDF](moneva_2022_alerting_consciences_to_reduce_cybercrime.pdf)
-   [Access the data and the R code](https://osf.io/bpyj7/)
